### PR TITLE
Add MemoryConfigurationProvider

### PR DESCRIPTION
**Pull request by vchirikov**
Hi, we want to use `IppDotNetSdkForQuickBooksApiV3` without `appsettings.json` configuration. So I added option parameter for `IConfigReader` (also renamed this to `IConfigurationProvider`) and add `MemoryConfigurationProvider` for reading the `IppConfiguration` from already created object.
Also removed unused code like `ApiSettings.cs`, `IApiSettings.cs ` and some trailing spaces.

### CODE REVIEW

**Comment by nimisha84** [comment]
Thanks for the Pull request. I will review it and update you in a day or two.

**Comment by nimisha84** [comment]
Looks good. Thanks

**Comment by nimisha84** [comment]
@vchirikov  had to make some changes in JsonFileConfigurationProvider to set base directory path to set default path. Just wanted to update you so that it does not breaks anything at your end. It was existing in the old LocalConfigReader and removing the base path has caused some of our sample app and tests to break. Hopefully, that should be ok with you.

**Comment by nimisha84** [comment]
public JsonFileConfigurationProvider(string path)
        {
            builder = new ConfigurationBuilder()
                **.SetBasePath(Directory.GetCurrentDirectory())**
                .AddJsonFile(path, optional: true)
                .Build();
           


        }

**Comment by vchirikov** [comment]
`optional: true` <- yep, with optional is ok for us, but will be better if you provide option for change base path without change current directory, because for example if you run code in IIS current directory will be `c:\windows\system32\inetsrv\` so your code search json in wrong location.
So I think you should change this fragment in future anyway.

**Pull request merged**
