### PR TITLE
Fix Build

### PR DESCRIPTION
**Pull request by dahlbyk**
Trying to update #221, but am unable to build `master`:

> warning NU1504: Duplicate 'PackageReference' items found. Remove the duplicate items or use the Update functionality to ensure a consistent restore behavior. The duplicate 'PackageReference' items are: Newtonsoft.Json 12.0.3, Newtonsoft.Json 13.0.1.

Managing dependencies with `Directory.Build.props` is relatively uncommon, and removing the `PackageReference` there mostly fixes it. Bumped to 13.0.2 while I'm at it.

Also had an issue building `Intuit.Ipp.Data.csproj` because it was showing `bin/` and `obj/` as part of the project. Never seen that before, but explicitly excluding them seems to fix it.

Highly recommend migrating from AppVeyor to GitHub Actions and keeping `master` green!

### CODE REVIEW

**Comment by dahlbyk** [comment]
> Add top-level .sln

Was hoping this would help the AppVeyor build not be confused, but apparently not. Still worth keeping the primary `.sln` at the top level, though, so folks don't have to go searching for the one in `IPPDotNetDevKitCSV3/Code/`.

**Comment by sujitharamadass** [comment]
We have already fixed these issues. Kindly take the latest from the master and let us know if you are still facing any issues.
AppVeyor for our project was never configured properly, so it always shows failed, but the build looks ok.

**Comment by sujitharamadass** [comment]
Take the latest from master and please update your PR
 then we can merge it for the rest of the changes

**Comment by nimisha84** [comment]
Please leave it as is for now. We do not want to update that for now. Thanks

**Comment by dahlbyk** [comment]
Resolved conflicts and brought back excluding `bin/` and `obj/`.

**Review by nimisha84 — APPROVED** [review]
Looks good. Thanks. @sujitharamadass please make sure that nuget package upload does not throw any errors that we saw earlier today.

**Pull request merged**
