### PR TITLE
Reports names

### PR DESCRIPTION
**Pull request by clement911**
Added class containing all the report names, so that they can be passed to `ReportService.ExecuteReport` method.

### CODE REVIEW

**Comment by clement911** [comment]
hi @nimisha84 ,do you need anything else from me before you can merge this?

**Comment by clement911** [comment]
@nimisha84 could you review this PR please?

**Comment by nimisha84** [comment]
Hi Clement, Sorry for the delay in responding here. I have moved to a different team and was just shadowing the other team on these PRs/SDK release. Can you elaborate more on why we need group_by when we do support groupby? Does some report need this variation? The PRs look good. I can approve them based on your answer

**Comment by nimisha84** [comment]
nvm, got the answer

**Pull request merged**
