### PR TITLE
CI pipeline using Github Actions and PS Core

### PR DESCRIPTION
**Pull request by andymac4182**
Hi,

This is an initial pipeline using Powershell core.

Basic build is done. Tests are commented out for the moment due to them failing the build. 

This is based on a reference project I created. andymac4182/andymac4182.Reference

Related to #145

### CODE REVIEW

**Comment by nimisha84** [comment]
Thanks for your PRs. Will review them and update you soon.

**Comment by andymac4182** [comment]
Thanks

**Comment by nimisha84** [comment]
Hi @andymac4182,

Do you have some time this week to go over your PR for CI? That ways it would be easier to review.

Thanks,
Nimisha

**Comment by andymac4182** [comment]
Yeah. I am in Brisbane, Australia. What time would be best?

**Comment by nimisha84** [comment]
Does tomorrow 2:30pm PST sound ok to you? I am in Mountainview, California

**Comment by andymac4182** [comment]
Yeah.

**Comment by nimisha84** [comment]
Please share you email so that I can send a meeting invite

**Comment by andymac4182** [comment]
andrew <dot> mcclenaghan <at> gmail.com

**Comment by nimisha84** [comment]
Discussed with Andy on the current release workflow we have in the project and this might conflict. Please see of you wanted to resubmit your PR after changes or not. I will close the PR accordingly.

**Pull request closed without merging**
