### PR TITLE
Add support for .Net Core 3.0 & 3.1

### PR DESCRIPTION
**Pull request by Zoullx**
Just added a Target Framework of netstandard2.1 in OAuth Client csproj to target .Net Core 3.0 & 3.1

### CODE REVIEW

**Comment by MatthewSteeples** [comment]
My understanding is that this shouldn't be necessary because .Net Core 3.0 and 3.1 (as well as .Net 5) will all happily use netstandard2.0. Are you seeing problems with this?

**Comment by Zoullx** [comment]
I have a .Net Core 3.1 Azure Function app that I want to use this with and without those changes the app won't run, everything just errors out. With those changes however the app works fine and is happy. Ans far as my understanding goes, .Net Standard 2.0 technically targets .Net Core 2.1 & 2.2, whereas .Net Standard 2.1 technically targets .Net Core 3.0 & 3.1 and I've actually ran into issues like that before with other libraries that only targeted .Net Standard 2.0 and not 2.1. Maybe this is mainly just an issue with Azure Function apps in .Net Core 3.1, but specifically targeting .Net Standard 2.1 fixes the issues.

**Comment by Zoullx** [comment]
Is there some more elaboration that you would like? Or do you want me to post exactly what is happening with my app?

**Comment by MatthewSteeples** [comment]
I'm personally very interested in the error (mainly because we're probably going to start using Azure Functions in the new year), but I don't work for Intuit or have any authority on this repository so I'm not sure here is the best place for it. If you're able to share the error or any details with me by email (matthew@mercuryit.co.uk) then I'm more than happy to see if it's anything I've encountered before

**Comment by MatthewSteeples** [comment]
After a couple of emails back and forth, it looke like [this commit](https://github.com/intuit/QuickBooks-V3-DotNET-SDK/commit/4fd35744a7f3b43c116bbab763e4f26fac883405) is the cause of the problems (version 14.4.2 works fine). Unless there was a need to update these packages, they are usually worth keeping "low". If someone is making use of them in their own project then they're usually forward compatible, but if you depend on a high version unnecessarily then you force all of their other references to get updated too, and in this case because Azure Functions can't handle .NET 5 it will no longer run.

If the library does need to update major versions of its dependencies, then it should update its own major version too to signify the change

**Comment by nimisha84** [comment]
There was another dev who had issues with Microsoft ReportViewer and he asked for the Abstractions package to the updated to latest. This was primarily the reason we did this update for all relevant packages to latest too. We update major version for release only when we have major api related updates. Is the above pull request solving for the issues related to Azure functions? I am on long PTO until Jan 4th but can look into this then. Let me know your thoughts.

**Comment by nimisha84** [comment]
Is this request still valid?

**Comment by Zoullx** [comment]
Sorry, been very busy. But, no, this request is not valid. I has only tested this with the library itself and did not install the dependencies of the library. As soon as I would have done that, things would have failed because of updating dependencies for my app up to 5.0 as Azure Functions aren't compatible with .Net Core 5.0 yet. The real fix, thanks to Matthew Steeples, was to revert to version 14.4.2 before the dependencies were updated to 5.0. This request can be closed as it will not do anything and is just a placebo effect.

**Comment by nimisha84** [comment]
Thanks for the update. We are releasing a fix version this week soon. Do not use 14.4.0 as this has dependency issues

**Pull request closed without merging**
